### PR TITLE
Feat : WishList Added

### PR DESCRIPTION
**Pull request by vikrantkode**
# Wishlist  Page Added

### CODE REVIEW

**Review by Pratham82 — COMMENTED** [review]
1. Remove some padding from the right, for the normal screen size of 1366 * 808 at least 3 card should show in a row, right now its only showing 2 cards, I think you can make use of this space.
image
2. Link of the brand is blue on  wishlist page

Only these things stood out for me, apart from this, good to go.

**Comment by vikrantkode** [comment]
> 1. Remove some padding from the right, for the normal screen size of 1366 * 808 at least 3 card should show in a row, right now its only showing 2 cards, I think you can make use of this space.
>    image
> 2. Link of the brand is blue on  wishlist page
> 
> Only these things stood out for me, apart from this, good to go.

for me its coming 3 in a row .... i think will have to look for responsiveness

**Comment by harshitpaliwal95** [comment]
> > 1. Remove some padding from the right, for the normal screen size of 1366 * 808 at least 3 card should show in a row, right now its only showing 2 cards, I think you can make use of this space.
> >    image
> > 2. Link of the brand is blue on  wishlist page
> > 
> > Only these things stood out for me, apart from this, good to go.
> 
> for me its coming 3 in a row .... i think will have to look for responsiveness

if u add margin: auto ; to card-container it will be fix try it

**Review by harshitpaliwal95 — APPROVED** [review]

**Comment by vikrantkode** [comment]
Screenshot (121)

# Changes Done

**Pull request merged**
